FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    xvfb \
    x11vnc \
    xterm \
    zsh \
    && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
COPY zshrc /etc/nowbox/zshrc
RUN chmod +x /entrypoint.sh

EXPOSE 5900

CMD ["/entrypoint.sh"]
